import * as React from 'react'
import { useAtom, useAtomValue, useSetAtom } from 'jotai'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { chatRoomApi } from '@/lib/chatroom-api'
import { openChatRoomTab, tabsAtom, activeTabIdAtom } from '@/atoms/tab-atoms'
import { agentWorkspacesAtom } from '@/atoms/agent-atoms'
import { chatRoomRoomsAtom } from '@/atoms/chatroom-atoms'

export function ChatroomCreateDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }): React.ReactElement {
  const [name, setName] = React.useState(''); const [code, setCode] = React.useState(''); const [error, setError] = React.useState(''); const [selected, setSelected] = React.useState<string[]>([]); const [progress, setProgress] = React.useState(0); const workspaces = useAtomValue(agentWorkspacesAtom); const [tabs, setTabs] = useAtom(tabsAtom); const [, setActive] = useAtom(activeTabIdAtom); const setRooms = useSetAtom(chatRoomRoomsAtom)
  const submit = async (event: React.FormEvent): Promise<void> => { event.preventDefault(); setError(''); if (!name.trim() || !/^[A-Z0-9]{4}$/.test(code.trim().toUpperCase())) { setError('请填写名称和4位分享码'); return } try { const room = await chatRoomApi.createRoom({ name: name.trim(), shareCode: code.trim().toUpperCase() }, selected.map((id) => ({ sourceWorkspaceId: id, displayName: workspaces.find((w) => w.id === id)?.name ?? 'Agent', channelId: '', contextMessageCount: 50, memorySharingEnabled: false, skillSharingEnabled: false }))); setProgress(selected.length); setRooms((current) => [...current.filter((item) => item.roomId !== room.roomId), room]); const next = openChatRoomTab(tabs, room); setTabs(next.tabs); setActive(next.activeTabId); onOpenChange(false); setName(''); setCode(''); setSelected([]); setProgress(0) } catch (e) { setError(e instanceof Error ? e.message : '创建聊天室失败'); setProgress(selected.length) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>创建聊天室</DialogTitle><DialogDescription>创建后可邀请成员加入，并选择最多3个本地 Agent</DialogDescription></DialogHeader><form onSubmit={(e) => void submit(e)} className="space-y-3"><input aria-label="聊天室名称" value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：产品讨论" className="w-full rounded-lg bg-muted px-3 py-2 outline-none" /><input aria-label="分享码" maxLength={4} value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="4位字母或数字" className="w-full rounded-lg bg-muted px-3 py-2 uppercase tracking-widest outline-none" /><div className="space-y-1"><div className="text-xs text-muted-foreground">选择 Agent（{selected.length}/3）</div>{workspaces.map((workspace) => <label key={workspace.id} className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-sm hover:bg-muted"><input type="checkbox" checked={selected.includes(workspace.id)} disabled={!selected.includes(workspace.id) && selected.length >= 3} onChange={() => setSelected((current) => current.includes(workspace.id) ? current.filter((id) => id !== workspace.id) : [...current, workspace.id])} />{workspace.name}</label>)}</div>{progress > 0 && <div role="status" className="text-xs text-muted-foreground">Agent 配置 {progress}/{selected.length}</div>}{error && <p role="alert" className="text-xs text-destructive">{error}</p>}<DialogFooter><Button type="button" variant="ghost" onClick={() => onOpenChange(false)}>取消</Button><Button type="submit">创建</Button></DialogFooter></form></DialogContent></Dialog>
}
