import * as React from 'react'
import type { ChatRoomAgent, ChatRoomMember, ChatRoomRole } from '@copis/shared'
import { chatRoomApi } from '@/lib/chatroom-api'

export interface ChatroomMembersPanelProps { roomId: string; role: ChatRoomRole; members: ChatRoomMember[]; agents: ChatRoomAgent[]; onChanged?: () => void }

export function ChatroomMembersPanel({ roomId, role, members, agents, onChanged }: ChatroomMembersPanelProps): React.ReactElement {
  const [busy, setBusy] = React.useState<string | null>(null)
  const updateSharing = async (agent: ChatRoomAgent, field: 'memorySharingEnabled' | 'skillSharingEnabled'): Promise<void> => { if (role !== 'host') return; setBusy(agent.agentId); try { await window.electronAPI.chatrooms.updateAgent({ roomId, roomAgentId: agent.agentId, [field]: field === 'memorySharingEnabled' ? !agent.memoryShared : !agent.skillsShared }); onChanged?.() } finally { setBusy(null) } }
  const syncSkills = async (agentId: string): Promise<void> => { if (role !== 'host') return; setBusy(agentId); try { await window.electronAPI.chatrooms.syncAgentSkills({ roomId, roomAgentId: agentId }); onChanged?.() } finally { setBusy(null) } }
  const removeAgent = async (agentId: string): Promise<void> => { setBusy(agentId); try { await window.electronAPI.chatrooms.removeAgent({ roomId, roomAgentId: agentId }); onChanged?.() } finally { setBusy(null) } }
  const removeMember = async (memberId: string): Promise<void> => { setBusy(memberId); try { await chatRoomApi.removeMember(roomId, memberId); onChanged?.() } finally { setBusy(null) } }
  return <aside aria-label="聊天室成员" className="w-64 shrink-0 border-l border-border/50 p-3 overflow-y-auto space-y-4">
    <section><h2 className="mb-2 text-xs font-semibold text-muted-foreground">成员 · {members.length}</h2><div className="space-y-1">{members.map((member) => <div key={member.userId} className="flex items-center justify-between rounded-lg bg-muted/30 px-2 py-1.5 text-xs"><span>{member.displayName}{member.role === 'host' && <span className="ml-1 text-primary">主理人</span>}</span><span className="flex items-center gap-1"><span className={member.presence === 'offline' ? 'text-muted-foreground' : 'text-emerald-500'}>{member.presence === 'offline' ? '离线' : member.presence === 'busy' ? '忙碌' : '在线'}</span>{role === 'host' && member.role !== 'host' && <button type="button" disabled={busy === member.userId} onClick={() => void removeMember(member.userId)} className="text-destructive">移除</button>}</span></div>)}</div></section>
    <section><h2 className="mb-2 text-xs font-semibold text-muted-foreground">Agent · {agents.length}/3</h2><div className="space-y-1">{agents.map((agent) => <div key={agent.agentId} className="rounded-lg bg-muted/30 px-2 py-1.5 text-xs"><div className="flex items-center justify-between"><span>@{agent.displayName}</span><span className={agent.status === 'offline' ? 'text-muted-foreground' : 'text-emerald-500'}>{agent.status === 'offline' ? '离线' : agent.status === 'busy' ? '忙碌' : '在线'}</span></div>{role === 'host' && <div className="mt-1 flex items-center gap-2 text-[10px] text-muted-foreground"><label><input type="checkbox" checked={agent.memoryShared} disabled={busy === agent.agentId} onChange={() => void updateSharing(agent, 'memorySharingEnabled')} /> 记忆</label><label><input type="checkbox" checked={agent.skillsShared} disabled={busy === agent.agentId} onChange={() => void updateSharing(agent, 'skillSharingEnabled')} /> Skill</label><button type="button" disabled={busy === agent.agentId} onClick={() => void syncSkills(agent.agentId)}>同步 Skill</button><button type="button" disabled={busy === agent.agentId} onClick={() => void removeAgent(agent.agentId)} className="text-destructive">移除</button></div>}</div>)}</div></section>
    {role === 'host' && <div className="border-t border-border/40 pt-3 text-[10px] text-muted-foreground">主理人权限：可在本机 Agent 设置中调整共享策略</div>}
  </aside>
}
