import { describe, expect, test } from 'bun:test'
import { createStore } from 'jotai/vanilla'
import { chatRoomActiveRoomIdAtom, chatRoomApplyEventAtom, chatRoomConnectionStatusAtom, chatRoomCursorsAtom, chatRoomDeletedRoomIdsAtom, chatRoomDetailsAtom, chatRoomDraftsAtom, chatRoomInvocationsAtom, chatRoomMessagesAtom, chatRoomRemoveRoomAtom, chatRoomResetStateAtom, chatRoomRoomsAtom, chatRoomSendMessageAtom, chatRoomSendStatesAtom, chatRoomTransfersAtom, chatRoomUnreadCountsAtom } from './chatroom-atoms'
describe('chatRoomAtoms', () => {
  test('同一 roomId 的消息与未读互不污染', () => { const store = createStore(); store.set(chatRoomActiveRoomIdAtom, 'r2'); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r1', seq: 1, payload: { messageId: 'm1' } }); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r2', seq: 1, payload: { messageId: 'm2' } }); expect(store.get(chatRoomMessagesAtom).get('r1')).toHaveLength(1); expect(store.get(chatRoomMessagesAtom).get('r2')).toHaveLength(1); expect(store.get(chatRoomUnreadCountsAtom).get('r1')).toBe(1); expect(store.get(chatRoomUnreadCountsAtom).get('r2')).toBeUndefined() })
  test('Agent 完成或失败清除 delta 并保留终态', () => { const store = createStore(); store.set(chatRoomApplyEventAtom, { type: 'agent.delta', roomId: 'r1', payload: { invocationId: 'i1', delta: '处理中' } }); store.set(chatRoomApplyEventAtom, { type: 'agent.failed', roomId: 'r1', payload: { invocationId: 'i1', failureCode: 'agent_offline' } }); const invocation = store.get(chatRoomInvocationsAtom).get('r1')?.get('i1'); expect(invocation?.status).toBe('failed'); expect(invocation?.delta).toBeUndefined(); expect(invocation?.failureCode).toBe('agent_offline') })
  test('失败发送可复用同一 clientMessageId，且不建立队列', async () => { const store = createStore(); const calls: string[] = []; const api = { sendMessage: async (input: { clientMessageId: string }) => { calls.push(input.clientMessageId); throw new Error('offline') } }; await expect(store.set(chatRoomSendMessageAtom, { api, roomId: 'r1', content: 'x', mentionAgentIds: [], attachmentIds: [], clientMessageId: 'c1' })).rejects.toThrow('offline'); expect(store.get(chatRoomSendStatesAtom).get('c1')).toMatchObject({ status: 'failed' }); expect(calls).toEqual(['c1']) })
  test('SSE message.created 使用真实 sender/text 字段写入标准消息', () => { const store = createStore(); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r1', seq: 4, payload: { messageId: 'm-4', sender: { type: 'agent', id: 'a-1', displayName: '助理' }, text: '完成', createdAt: 1720000000000, mentionedAgentIds: ['a-2'], attachmentIds: [] } }); expect(store.get(chatRoomMessagesAtom).get('r1')?.[0]).toMatchObject({ messageId: 'm-4', senderType: 'agent', senderId: 'a-1', content: '完成', mentionAgentIds: ['a-2'], createdAt: '1720000000000' }) })
  test('注销或切换账号时清空所有账号范围聊天室状态', () => { const store = createStore(); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'old', seq: 1, payload: { messageId: 'm-old', sender: { type: 'user', id: 'u-a' }, text: '旧账号', createdAt: 1 } }); store.set(chatRoomDraftsAtom, new Map([['old', '草稿']])); store.set(chatRoomResetStateAtom); expect(store.get(chatRoomMessagesAtom).size).toBe(0); expect(store.get(chatRoomCursorsAtom).size).toBe(0); expect(store.get(chatRoomDraftsAtom).size).toBe(0); expect(store.get(chatRoomUnreadCountsAtom).size).toBe(0); expect(store.get(chatRoomSendStatesAtom).size).toBe(0) })
  test('删除房间清理全部客户端状态并阻止迟到事件复活', () => {
    const store = createStore()
    store.set(chatRoomRoomsAtom, [{ roomId: 'r1', name: '房间', role: 'member', status: 'active', memberCount: 1, unreadCount: 1, connectionStatus: 'connected' }])
    store.set(chatRoomDetailsAtom, { r1: { room: '详情' } })
    store.set(chatRoomMessagesAtom, new Map([['r1', []]])); store.set(chatRoomCursorsAtom, new Map([['r1', 4]])); store.set(chatRoomConnectionStatusAtom, new Map([['r1', 'connected']]))
    store.set(chatRoomDraftsAtom, new Map([['r1', '草稿']])); store.set(chatRoomUnreadCountsAtom, new Map([['r1', 2]])); store.set(chatRoomInvocationsAtom, new Map([['r1', new Map()]])); store.set(chatRoomTransfersAtom, new Map([['t1', { transferId: 't1', roomId: 'r1', phase: 'uploading', progress: 0 }]]))
    store.set(chatRoomActiveRoomIdAtom, 'r1'); store.set(chatRoomRemoveRoomAtom, 'r1')
    expect(store.get(chatRoomRoomsAtom)).toEqual([]); expect(store.get(chatRoomDetailsAtom)).toEqual({}); expect(store.get(chatRoomMessagesAtom).has('r1')).toBe(false); expect(store.get(chatRoomCursorsAtom).has('r1')).toBe(false); expect(store.get(chatRoomConnectionStatusAtom).has('r1')).toBe(false); expect(store.get(chatRoomDraftsAtom).has('r1')).toBe(false); expect(store.get(chatRoomUnreadCountsAtom).has('r1')).toBe(false); expect(store.get(chatRoomInvocationsAtom).has('r1')).toBe(false); expect(store.get(chatRoomTransfersAtom).size).toBe(0); expect(store.get(chatRoomActiveRoomIdAtom)).toBeUndefined()
    store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r1', seq: 5, payload: { messageId: 'late' } })
    expect(store.get(chatRoomMessagesAtom).has('r1')).toBe(false); expect(store.get(chatRoomDeletedRoomIdsAtom).has('r1')).toBe(true)
  })
})
