import { describe, expect, test } from 'bun:test'
import { createStore } from 'jotai/vanilla'
import { chatRoomActiveRoomIdAtom, chatRoomApplyEventAtom, chatRoomInvocationsAtom, chatRoomMessagesAtom, chatRoomSendMessageAtom, chatRoomSendStatesAtom, chatRoomUnreadCountsAtom } from './chatroom-atoms'
describe('chatRoomAtoms', () => {
  test('同一 roomId 的消息与未读互不污染', () => { const store = createStore(); store.set(chatRoomActiveRoomIdAtom, 'r2'); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r1', seq: 1, payload: { messageId: 'm1' } }); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r2', seq: 1, payload: { messageId: 'm2' } }); expect(store.get(chatRoomMessagesAtom).get('r1')).toHaveLength(1); expect(store.get(chatRoomMessagesAtom).get('r2')).toHaveLength(1); expect(store.get(chatRoomUnreadCountsAtom).get('r1')).toBe(1); expect(store.get(chatRoomUnreadCountsAtom).get('r2')).toBeUndefined() })
  test('Agent 完成或失败清除 delta 并保留终态', () => { const store = createStore(); store.set(chatRoomApplyEventAtom, { type: 'agent.delta', roomId: 'r1', payload: { invocationId: 'i1', delta: '处理中' } }); store.set(chatRoomApplyEventAtom, { type: 'agent.failed', roomId: 'r1', payload: { invocationId: 'i1', failureCode: 'agent_offline' } }); const invocation = store.get(chatRoomInvocationsAtom).get('r1')?.get('i1'); expect(invocation?.status).toBe('failed'); expect(invocation?.delta).toBeUndefined(); expect(invocation?.failureCode).toBe('agent_offline') })
  test('失败发送可复用同一 clientMessageId，且不建立队列', async () => { const store = createStore(); const calls: string[] = []; const api = { sendMessage: async (input: { clientMessageId: string }) => { calls.push(input.clientMessageId); throw new Error('offline') } }; await expect(store.set(chatRoomSendMessageAtom, { api, roomId: 'r1', content: 'x', mentionAgentIds: [], attachmentIds: [], clientMessageId: 'c1' })).rejects.toThrow('offline'); expect(store.get(chatRoomSendStatesAtom).get('c1')).toMatchObject({ status: 'failed' }); expect(calls).toEqual(['c1']) })
  test('SSE message.created 使用真实 sender/text 字段写入标准消息', () => { const store = createStore(); store.set(chatRoomApplyEventAtom, { type: 'message.created', roomId: 'r1', seq: 4, payload: { messageId: 'm-4', sender: { type: 'agent', id: 'a-1', displayName: '助理' }, text: '完成', createdAt: 1720000000000, mentionedAgentIds: ['a-2'], attachmentIds: [] } }); expect(store.get(chatRoomMessagesAtom).get('r1')?.[0]).toMatchObject({ messageId: 'm-4', senderType: 'agent', senderId: 'a-1', content: '完成', mentionAgentIds: ['a-2'], createdAt: '1720000000000' }) })
})
