import { describe, expect, test } from 'bun:test'
import { ChatRoomSseClient, parseChatRoomSseFrame } from './chatroom-sse'
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status })
describe('chatRoomSse', () => {
  test('解析 event/data 多行帧', () => { expect(parseChatRoomSseFrame('event: message.created\ndata: {"type":"message.created",\ndata: "roomId":"r1"}\n\n')?.type).toBe('message.created') })
  test('多房间查询保留逗号且 close 会停止请求', async () => { const urls: string[] = []; const statuses: string[] = []; let resolve!: () => void; const api = new ChatRoomSseClient({ baseUrl: 'http://test', fetchImpl: async (url, init) => { urls.push(String(url)); await new Promise<void>((r) => { resolve = r; init?.signal?.addEventListener('abort', () => r()) }); throw new DOMException('aborted', 'AbortError') } }); api.onStatus((s) => statuses.push(s)); api.setRooms(['r1', 'r2']); await Promise.resolve(); expect(urls[0]).toContain('roomIds=r1,r2'); api.close(); resolve?.(); expect(statuses).toContain('offline') })
  test('缺少 type 的帧被丢弃', () => { expect(parseChatRoomSseFrame('event: message.created\ndata: {"payload":{}}\n\n')).toBeUndefined() })
  test('重连前按每个房间游标补拉断线期间的持久事件并处理订阅窗口事件', async () => { let calls = 0; const received: number[] = []; const stream = (body: string) => new Response(new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode(body)); controller.close() } }), { headers: { 'Content-Type': 'text/event-stream' } }); const api = new ChatRoomSseClient({ baseUrl: 'http://test', fetchImpl: async (url) => { calls++; if (String(url).includes('/events?roomIds=')) return stream(calls === 1 ? 'data: {"type":"message.created","roomId":"r1","seq":1,"payload":{}}\n\n' : 'data: {"type":"message.created","roomId":"r1","seq":3,"payload":{}}\n\n'); return response({ data: [{ eventType: 'message.created', roomId: 'r1', seq: 2, payload: {} }] }) } }); api.onEvent((event) => { if (event.seq) received.push(event.seq) }); api.setRooms(['r1']); await new Promise((resolve) => setTimeout(resolve, 350)); api.close(); expect(calls).toBeGreaterThanOrEqual(3); expect(received).toEqual([1, 2, 3]) })
  test('恢复分页超过 500 条仍按序读取且有上限', async () => { let calls = 0; const stream = (body: string) => new Response(new ReadableStream({ start(controller) { controller.enqueue(new TextEncoder().encode(body)); controller.close() } }), { headers: { 'Content-Type': 'text/event-stream' } }); const received: number[] = []; const api = new ChatRoomSseClient({ baseUrl: 'http://test', fetchImpl: async (url) => { calls++; if (String(url).includes('/events?roomIds=')) return stream('data: {"type":"message.created","roomId":"r1","seq":1,"payload":{}}\n\n'); const after = Number(new URL(String(url)).searchParams.get('afterSeq')); const start = after + 1; const end = start + (start === 2 ? 499 : 1); return response({ data: Array.from({ length: end - start + 1 }, (_, index) => ({ eventType: 'message.created', roomId: 'r1', seq: start + index, payload: {} })) }) } }); api.onEvent((event) => { if (event.seq) received.push(event.seq) }); api.setRooms(['r1']); await new Promise((resolve) => setTimeout(resolve, 350)); api.close(); expect(Math.max(...received)).toBeGreaterThanOrEqual(501) })
  test('401 后 auth 恢复可显式 resume', async () => { let calls = 0; const api = new ChatRoomSseClient({ baseUrl: 'http://test', fetchImpl: async () => { calls++; return calls === 1 ? new Response(null, { status: 401 }) : new Response(null, { status: 200, headers: { 'Content-Type': 'text/event-stream' } }) } }); api.setRooms(['r1']); await Promise.resolve(); api.resume(); await Promise.resolve(); expect(calls).toBe(2); api.close() })
})
