import ICONS from "./icons.js";

const byId = Object.fromEntries(ICONS.map(item => [item.id, item.src]));

export const PRESET_BASE = {
  rank: { showDecor: true, decorSrc: byId["10"] },
  table: { showDecor: true, decorSrc: byId["11"] },
  quadrant: { showDecor: true, decorSrc: byId["12"] },
  chain: { showDecor: true, decorSrc: byId["03"] },
  case: { showDecor: true, decorSrc: byId["07"] },
  spotlight: { showDecor: true, decorSrc: byId["02"] },
  coreweave: { showDecor: true, decorSrc: byId["09"] },
  casecompare: { showDecor: true, decorSrc: byId["11"] },
  section: { showDecor: true, decorSrc: byId["08"] },
  round: { showDecor: true, decorSrc: byId["06"] },
  monthly: { showDecor: true, decorSrc: byId["09"] },
  stat: { showDecor: true, decorSrc: byId["05"] },
  valuationjump: { showDecor: true, decorSrc: byId["06"] },
  valuation: { showDecor: true, decorSrc: byId["12"] },
  risk: { showDecor: true, decorSrc: byId["04"] },
  riskchain: { showDecor: true, decorSrc: byId["03"] },
  outlook: { showDecor: true, decorSrc: byId["02"] },
  timeline: { showDecor: true, decorSrc: byId["06"] },
  takeaway: { showDecor: true, decorSrc: byId["05"] },
  quote: { showDecor: true, decorSrc: byId["01"] },
  aarrr: { showDecor: true, decorSrc: byId["06"] },
  rfm: { showDecor: true, decorSrc: byId["12"] },
  maba: { showDecor: true, decorSrc: byId["03"] },
  gantt: { showDecor: true, decorSrc: byId["11"] },
  doublediamond: { showDecor: true, decorSrc: byId["02"] },
  swot: { showDecor: true, decorSrc: byId["03"] },
  fiveforces: { showDecor: true, decorSrc: byId["10"] },
  canvas: { showDecor: true, decorSrc: byId["11"] },
  journey: { showDecor: true, decorSrc: byId["09"] },
  pyramid: { showDecor: true, decorSrc: byId["12"] },
  bcg: { showDecor: false, quadIcons: [byId["10"], byId["04"], byId["12"], byId["03"]] },
  flywheel: { showDecor: true, decorSrc: byId["05"] },
  pest: { showDecor: true, decorSrc: byId["08"] },
  pareto: { showDecor: true, decorSrc: byId["06"] },
  radar: { showDecor: true, decorSrc: byId["04"] },
  shift: { showDecor: true, decorSrc: byId["01"] },
  betmatrix: { showDecor: true, decorSrc: byId["02"] },
  share: { showDecor: true, decorSrc: byId["05"] },
  waterfall: { showDecor: true, decorSrc: byId["06"] },
  treemap: { showDecor: true, decorSrc: byId["03"] },
  escalation: { showDecor: true, decorSrc: byId["10"] },
  sankey: { showDecor: true, decorSrc: byId["06"] },
  scorecard: { showDecor: true, decorSrc: byId["11"] },
  gauge: { showDecor: true, decorSrc: byId["04"] },
  rose: { showDecor: true, decorSrc: byId["06"] },
  marimekko: { showDecor: true, decorSrc: byId["03"] },
  concentration: { showDecor: true, decorSrc: byId["10"] },
  tornado: { showDecor: true, decorSrc: byId["06"] },
  bubble: { showDecor: true, decorSrc: byId["06"] },
  chronicle: { showDecor: true, decorSrc: byId["06"] },
  register: { showDecor: true, decorSrc: byId["04"] },
  waffle: { showDecor: true, decorSrc: byId["06"] },
  peak: { showDecor: true, decorSrc: byId["05"] },
  cumulative: { showDecor: true, decorSrc: byId["06"] },
  hypecycle: { showDecor: true, decorSrc: byId["04"] },
  horizon: { showDecor: true, decorSrc: byId["02"] },
  layertable: { showDecor: true, decorSrc: byId["11"] },
  moat: { showDecor: true, decorSrc: byId["10"] },
  supply: { showDecor: true, decorSrc: byId["04"] },
  colophon: { showDecor: true, decorSrc: byId["10"] },
};

export default PRESET_BASE;
