import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { buildSync } from 'esbuild';
import {
  LAYOUT_ALIASES,
  LAYOUT_OPTIONS,
  DEFAULT_THEME_PACK,
  THEME_PACK_OPTIONS,
  resolveOption,
} from './options.jsx';
import {
  buildDeckViewModel,
  renderDeckView,
  serializeDeckViewModel,
} from './view-model/index.jsx';
import {
  REQUIRED_OUTPUT_ASSETS,
  RUNTIME_ASSET_PATHS,
  RUNTIME_TEMPLATE,
} from './runtime-assets.mjs';
import {
  buildThemeRegistrySource,
  isFullThemeSet,
  normalizeThemeKeys,
} from './components/themes/theme-registry-codegen.mjs';
import { buildThemeRuntimeOverrideRegistrySource } from './components/themes/theme-overrides-registry-codegen.mjs';
import { buildBespokeThemeProfileRegistrySource } from './components/bespoke/theme-profile-registry-codegen.mjs';
import { normalizeDeckLanguage, buildDeckI18nDict } from './i18n.mjs';
import {
  buildClientRuntime,
  buildClientRuntimeFromModules,
  prebuiltBespokeModulePath,
  prebuiltBundlePath,
  prebuiltModulePath,
  prebuiltThemeOverrideModulePath,
  prebuiltThemeProfileModulePath,
} from './components/themes/runtime-build.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const FULL_THEME_REGISTRY = path.join(ROOT, 'src/components/themes/theme-registry.jsx');
const MIGRATION_ONLY_DIRS = new Set(['uploads', 'screens', 'screenshots', 'shots', 'scratch']);

export function renderDeck(deck, { outFile, includeThemeSwitcher = deck.preview?.themeSwitcher === true }) {
  const viewModel = buildDeckViewModel(deck, {
    layouts: LAYOUT_OPTIONS,
    layoutAliases: LAYOUT_ALIASES,
    themePacks: THEME_PACK_OPTIONS,
    defaultThemePack: DEFAULT_THEME_PACK,
    resolveOption,
  });
  const { key: themePackName } = viewModel.themePack;
  const language = normalizeDeckLanguage(deck.language);
  const template = fs.readFileSync(path.join(ROOT, RUNTIME_TEMPLATE), 'utf8');
  const slides = renderToStaticMarkup(<>{renderDeckView(viewModel)}</>);
  let html = insertSlides(template, slides);
  const htmlLang = language === 'en' ? 'en' : 'zh-CN';
  html = html.replace('<html lang="zh-CN">', `<html lang="${htmlLang}" data-theme-pack="${themePackName}">`);
  html = html.replace('<title>[必填] 替换为 PPT 标题 · Deck Title</title>', `<title>${escapeHtml(viewModel.model.title)}</title>`);
  html = injectPreviewOptions(html, viewModel.options, { includeThemeSwitcher, language, viewModel });
  html = injectDeckViewModel(html, serializeDeckViewModel(viewModel));

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, html);
  copyRuntimeAssets(path.dirname(outFile), { usedThemeKeys: collectUsedThemeKeys(viewModel) });
}

// JAD-201:从 deck 实际用到的主题(每页 themePack)推导待打包的主题集合。
function collectUsedThemeKeys(viewModel) {
  const keys = new Set();
  for (const slide of viewModel.slides || []) {
    for (const variant of slide.variants || [slide]) {
      if (variant.themePack) keys.add(variant.themePack);
    }
  }
  return normalizeThemeKeys(keys);
}

function insertSlides(template, slides) {
  const startMatch = template.match(/<div id="deck"[^>]*>/);
  const startTag = startMatch?.[0];
  const start = startMatch?.index ?? -1;
  const nav = template.indexOf('<div id="nav"', start);
  const deckEnd = findClosingDiv(template, start);

  if (start === -1 || nav === -1 || deckEnd === -1) {
    throw new Error('Template is missing <div id="deck"> or <div id="nav"> markers.');
  }

  const before = template.slice(0, start + startTag.length);
  const after = template.slice(deckEnd);
  return `${before}\n\n<!-- Generated by scripts/render-deck.jsx -->\n${slides}\n\n${after}`;
}

function findClosingDiv(html, start) {
  if (start < 0) return -1;
  const tagPattern = /<\/?div\b[^>]*>/gi;
  tagPattern.lastIndex = start;
  let depth = 0;
  let match;
  while ((match = tagPattern.exec(html))) {
    if (match[0].startsWith('</')) {
      depth -= 1;
      if (depth === 0) return match.index;
    } else {
      depth += 1;
    }
  }
  return -1;
}

function injectPreviewOptions(html, options, { includeThemeSwitcher = false, language = 'zh', viewModel = null } = {}) {
  const previewOptions = {
    ...options,
    themePacks: includeThemeSwitcher ? options.themePacks : {},
    // 多主题调试总览(showcase)不自动保存:它是共享调试产物,浏览器里的试验性编辑
    // 不应烧回 index.html(会污染 render:themes 与其上运行的其他测试)。
    ...(includeThemeSwitcher ? { autosave: false } : {}),
    language,
    // 词典子集始终注入(按本 deck 用到的页面裁剪,通常几 KB):运行时语言可由
    // 系统语言/用户手动切换决定,中文 deck 也可能要切到英文界面。
    ...(viewModel ? { i18n: buildDeckI18nDict(viewModel) } : {}),
  };
  const json = escapeScriptJson(JSON.stringify(previewOptions));
  return html.replace(
    /<script id="preview-options" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="preview-options" type="application/json">${json}</script>`,
  );
}

function injectDeckViewModel(html, viewModel) {
  const json = escapeScriptJson(JSON.stringify(viewModel));
  return html.replace(
    /<script id="deck-view-model" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="deck-view-model" type="application/json">${json}</script>`,
  );
}

function copyRuntimeAssets(outDir, { usedThemeKeys = [] } = {}) {
  const assetsDir = path.join(outDir, 'assets');
  const imagesDir = path.join(outDir, 'images');
  const preservedUserMedia = preserveUserMediaDirs(outDir);
  try {
    [assetsDir, imagesDir, path.join(outDir, 'uploads'), path.join(outDir, 'screens'), path.join(outDir, 'screenshots')].forEach(dir => {
      fs.rmSync(dir, { recursive: true, force: true });
    });
    fs.mkdirSync(assetsDir, { recursive: true });
    copyRequiredFile(path.join(ROOT, 'node_modules/gsap/dist/gsap.min.js'), path.join(assetsDir, 'vendor/gsap.min.js'));
    copyRequiredFile(path.join(ROOT, 'node_modules/pptxgenjs/dist/pptxgen.bundle.js'), path.join(assetsDir, 'vendor/pptxgen.bundle.js'));
    copyRequiredFile(path.join(ROOT, 'node_modules/pdf-lib/dist/pdf-lib.min.js'), path.join(assetsDir, 'vendor/pdf-lib.min.js'));
    copyRequiredFile(path.join(ROOT, 'node_modules/html-to-image/dist/html-to-image.js'), path.join(assetsDir, 'vendor/html-to-image.js'));
    for (const assetPath of RUNTIME_ASSET_PATHS) {
      if (assetPath === RUNTIME_TEMPLATE) continue;
      copyRuntimeAsset(assetPath, outDir);
    }
    copyImportedThemeAssets(outDir, usedThemeKeys);
    buildImportedThemeRuntime(path.join(assetsDir, 'imported-theme-runtime.js'), usedThemeKeys);
    restoreUserMediaDirs(preservedUserMedia, outDir);
    const imageSlotStateFile = path.join(outDir, '.image-slots.state.json');
    if (!fs.existsSync(imageSlotStateFile)) fs.writeFileSync(imageSlotStateFile, '{}\n');
  } finally {
    cleanupPreservedUserMedia(preservedUserMedia);
  }
}

function copyRuntimeAsset(assetPath, outDir) {
  const source = path.join(ROOT, assetPath);
  const target = path.join(outDir, assetPath);
  if (!fs.existsSync(source)) {
    throw new Error(`Runtime asset is listed but missing: ${assetPath}`);
  }
  if (fs.statSync(source).isDirectory()) {
    copyDirectoryIfExists(source, target);
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(source, target);
  }
}

function preserveUserMediaDirs(outDir) {
  const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'dashi-user-media-'));
  const entries = [
    ['assets/user-media', path.join(outDir, 'assets/user-media')],
    ['images/user-media', path.join(outDir, 'images/user-media')],
  ].filter(([, source]) => fs.existsSync(source));

  entries.forEach(([relative, source]) => {
    copyDirectoryIfExists(source, path.join(tempRoot, relative));
  });

  return { tempRoot, entries: entries.map(([relative]) => relative) };
}

function restoreUserMediaDirs(preserved, outDir) {
  for (const relative of preserved.entries) {
    copyDirectoryIfExists(path.join(preserved.tempRoot, relative), path.join(outDir, relative));
  }
}

function cleanupPreservedUserMedia(preserved) {
  fs.rmSync(preserved.tempRoot, { recursive: true, force: true });
}

// JAD-201/203:打包这份 deck 实际用到主题的浏览器运行时。两条等价路径(见 runtime-build.mjs):
//   - dev / 有主题源(showcase 全主题、本地迭代):源 esbuild(行为同 JAD-201)。
//   - 安装版 / 无可读主题源:单主题拷贝预构建自包含 bundle;多主题用预构建模块链接。
// `DASHI_PPT_THEME_RUNTIME`:auto(默认,有源走源、无源走预构建)| prebuilt(强制预构建,测试用)
//   | source(强制源)。安装版无主题源时自动走预构建,产出与源路径等价(单一 React,水合一致)。
function buildImportedThemeRuntime(outFile, usedThemeKeys = []) {
  const normalized = normalizeThemeKeys(usedThemeKeys || []);
  const mode = process.env.DASHI_PPT_THEME_RUNTIME || 'auto';
  const sourcePresent = hasThemeSource(normalized);
  const wantPrebuilt = mode === 'prebuilt' || (mode === 'auto' && !sourcePresent);

  if (wantPrebuilt) {
    // 单主题(绝大多数 deck):直接拷贝预构建自包含 bundle —— 零 deck 级 esbuild、零主题源。
    if (normalized.length === 1) {
      const bundle = prebuiltBundlePath(ROOT, normalized[0]);
      if (fs.existsSync(bundle)) {
        fs.copyFileSync(bundle, outFile);
        return;
      }
    }
    // 多主题(或单主题缺自包含 bundle):用预构建 minified 模块链接(无主题源)。
    if (normalized.length && prebuiltModulesAvailable(normalized)) {
      buildClientRuntimeFromModules({ root: ROOT, outFile, themeKeys: normalized });
      return;
    }
    if (mode === 'prebuilt') {
      throw new Error(`prebuilt theme runtime requested but artifacts missing for [${normalized.join(', ')}]; run \`node scripts/build/build-theme-runtime.mjs\`.`);
    }
    // mode=auto 且无源、无预构建:落到下方报错。
  }

  if (sourcePresent && mode !== 'prebuilt') {
    buildImportedThemeRuntimeFromSource(outFile, normalized);
    return;
  }

  throw new Error(`No imported theme runtime available for [${normalized.join(', ')}] (no readable theme source and no prebuilt artifacts).`);
}

// 源路径(JAD-201):别名指向全主题签入注册表或按 usedThemeKeys 裁剪的源注册表。
function buildImportedThemeRuntimeFromSource(outFile, usedThemeKeys = []) {
  const themeRegistry = resolveThemeRegistryEntry(usedThemeKeys);
  const profileRegistry = resolveBespokeProfileRegistryEntry(usedThemeKeys);
  const overrideRegistry = resolveThemeRuntimeOverrideRegistryEntry(usedThemeKeys);
  try {
    buildClientRuntime({
      root: ROOT,
      outFile,
      registryPath: themeRegistry.registryPath,
      bespokeProfilesPath: profileRegistry.registryPath,
      themeOverridesPath: overrideRegistry.registryPath,
    });
  } finally {
    themeRegistry.cleanup();
    profileRegistry.cleanup();
    overrideRegistry.cleanup();
  }
}

// 主题源是否在盘上(dev 仓为真;安装版已删 runtime.jsx + theme-registry.jsx,为假)。
function hasThemeSource(normalized) {
  if (!normalized.length) return fs.existsSync(FULL_THEME_REGISTRY);
  return normalized.every(key => fs.existsSync(path.join(ROOT, 'src/components/themes', key, 'runtime.jsx')));
}

function prebuiltModulesAvailable(normalized) {
  return normalized.length > 0
    && fs.existsSync(prebuiltBespokeModulePath(ROOT))
    && normalized.every(key => (
      fs.existsSync(prebuiltModulePath(ROOT, key))
      && fs.existsSync(prebuiltThemeProfileModulePath(ROOT, key))
      && fs.existsSync(prebuiltThemeOverrideModulePath(ROOT, key))
    ));
}

// 全主题(或主题集合无法识别时)→ 直接用签入的全主题注册表;
// 单/少主题 → 生成裁剪版临时注册表(写到 gitignore 的 node_modules/.cache,
// import 用指向仓库的绝对路径,确保从临时位置也能解析主题源码与 react)。
function resolveThemeRegistryEntry(usedThemeKeys) {
  const normalized = normalizeThemeKeys(usedThemeKeys || []);
  if (!normalized.length || isFullThemeSet(normalized)) {
    return { registryPath: FULL_THEME_REGISTRY, cleanup: () => {} };
  }
  const importPrefix = `${path.join(ROOT, 'src/components/themes')}/`;
  const source = buildThemeRegistrySource(normalized, { importPrefix });
  const cacheDir = path.join(ROOT, 'node_modules/.cache/dashi-theme-registry');
  fs.mkdirSync(cacheDir, { recursive: true });
  const registryPath = path.join(
    cacheDir,
    `registry-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}.jsx`,
  );
  fs.writeFileSync(registryPath, source);
  return {
    registryPath,
    cleanup: () => { try { fs.rmSync(registryPath, { force: true }); } catch {} },
  };
}

function resolveBespokeProfileRegistryEntry(usedThemeKeys) {
  const normalized = normalizeThemeKeys(usedThemeKeys || []);
  const fullRegistry = path.join(ROOT, 'src/components/bespoke/theme-profiles.mjs');
  if (!normalized.length || isFullThemeSet(normalized)) {
    return { registryPath: fullRegistry, cleanup: () => {} };
  }
  const importPrefix = `${path.join(ROOT, 'src/components/bespoke')}${path.sep}`;
  const source = buildBespokeThemeProfileRegistrySource(normalized, { importPrefix });
  const cacheDir = path.join(ROOT, 'node_modules/.cache/dashi-theme-registry');
  fs.mkdirSync(cacheDir, { recursive: true });
  const registryPath = path.join(
    cacheDir,
    `bespoke-profile-registry-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}.mjs`,
  );
  fs.writeFileSync(registryPath, source);
  return {
    registryPath,
    cleanup: () => { try { fs.rmSync(registryPath, { force: true }); } catch {} },
  };
}

function resolveThemeRuntimeOverrideRegistryEntry(usedThemeKeys) {
  const normalized = normalizeThemeKeys(usedThemeKeys || []);
  const fullRegistry = path.join(ROOT, 'src/components/themes/theme-overrides.mjs');
  if (!normalized.length || isFullThemeSet(normalized)) {
    return { registryPath: fullRegistry, cleanup: () => {} };
  }
  const importPrefix = `${path.join(ROOT, 'src/components/themes')}${path.sep}`;
  const source = buildThemeRuntimeOverrideRegistrySource(normalized, { importPrefix });
  const cacheDir = path.join(ROOT, 'node_modules/.cache/dashi-theme-registry');
  fs.mkdirSync(cacheDir, { recursive: true });
  const registryPath = path.join(
    cacheDir,
    `theme-override-registry-${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}.mjs`,
  );
  fs.writeFileSync(registryPath, source);
  return {
    registryPath,
    cleanup: () => { try { fs.rmSync(registryPath, { force: true }); } catch {} },
  };
}

function copyImportedThemeAssets(outDir, usedThemeKeys = []) {
  const themesDir = path.join(ROOT, 'src/components/themes');
  if (!fs.existsSync(themesDir)) return;
  // JAD-201: a deck only needs its used theme(s)' assets. Empty/all-themes (e.g.
  // the showcase) copies everything; a single-/few-theme deck skips the rest,
  // shrinking the deck and not leaking other themes' image/video source assets.
  const usedFilter = new Set(usedThemeKeys || []);
  const copiedByRelativePath = new Map(
    REQUIRED_OUTPUT_ASSETS.map(assetPath => [
      assetPath,
      { themeKey: 'runtime', from: path.join(ROOT, assetPath) },
    ]),
  );
  for (const themeKey of fs.readdirSync(themesDir).sort()) {
    if (usedFilter.size > 0 && !usedFilter.has(themeKey)) continue;
    const sourceDir = path.join(themesDir, themeKey, 'source');
    if (!fs.existsSync(sourceDir)) continue;
    const files = [];
    collectThemeAssetFiles(sourceDir, files);
    files.forEach(from => {
      const rel = path.relative(sourceDir, from);
      const outputRel = rel.replaceAll(path.sep, '/');
      const existing = copiedByRelativePath.get(outputRel);
      if (existing) {
        throw new Error(`Theme asset output path collision: ${outputRel} (${existing.themeKey}: ${existing.from}, ${themeKey}: ${from})`);
      }
      copiedByRelativePath.set(outputRel, { themeKey, from });
      const to = path.join(outDir, rel);
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(from, to);
    });
  }
}

function collectThemeAssetFiles(dir, out) {
  for (const name of fs.readdirSync(dir).sort()) {
    const file = path.join(dir, name);
    const stat = fs.statSync(file);
    if (stat.isDirectory()) {
      if (MIGRATION_ONLY_DIRS.has(name.toLowerCase())) continue;
      collectThemeAssetFiles(file, out);
      continue;
    }
    if (/\.(png|jpe?g|webp|gif|svg|mp4|mov)$/i.test(name)) out.push(file);
  }
}

function copyDirectoryIfExists(from, to) {
  if (!fs.existsSync(from)) return;
  for (const name of fs.readdirSync(from)) {
    const source = path.join(from, name);
    const target = path.join(to, name);
    const stat = fs.statSync(source);
    if (stat.isDirectory()) {
      copyDirectoryIfExists(source, target);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(source, target);
    }
  }
}

function copyFileIfExists(from, to) {
  if (fs.existsSync(from)) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

// 交付件必需的 vendor 库缺失时立刻失败,不允许静默产出缺脚本的 deck。
function copyRequiredFile(from, to) {
  if (!fs.existsSync(from)) {
    throw new Error(`Required vendor asset missing: ${from}`);
  }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeScriptJson(value) {
  return value
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}
